services:
  typebot-builder:
    image: baptistearno/typebot-builder:latest
    restart: always
    ports:
      - '8080:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: .env
    labels:
      virtual.host: 'typebotbuilder.whiteblinkcmds.com'
      virtual.port: '3000'
      virtual.tls-email: 'citizensprojects@whiteblink.com'

  typebot-viewer:
    image: baptistearno/typebot-viewer:latest
    restart: always
    ports:
      - '8081:3000'
    env_file: .env
    labels:
      virtual.host: 'typebotviewer.whiteblinkcmds.com'
      virtual.port: '3000'
      virtual.tls-email: 'citizensprojects@whiteblink.com'
  caddy-gen:
    container_name: caddy-gen
    image: 'wemakeservices/caddy-gen:latest'
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${PWD}/.typebot/caddy-certificates:/data/caddy
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - typebot-builder
      - typebot-viewer
